# Generated by Django 5.2.17 on 2026-08-07 15:43

import apps.core.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=32)),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('item_type', models.CharField(choices=[('RAW', 'RAW'), ('CONSUMABLE', 'CONSUMABLE'), ('PACKAGING', 'PACKAGING'), ('FINISHED', 'FINISHED')], default='RAW', max_length=16)),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('reorder_level', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('reorder_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('costing_method', models.CharField(choices=[('WEIGHTED_AVG', 'WEIGHTED_AVG'), ('FIFO', 'FIFO')], default='WEIGHTED_AVG', max_length=16)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_items',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('COUNTING', 'COUNTING'), ('REVIEW', 'REVIEW'), ('POSTED', 'POSTED'), ('CANCELLED', 'CANCELLED')], default='DRAFT', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_counts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('OPENING', 'OPENING'), ('PURCHASE', 'PURCHASE'), ('SALE', 'SALE'), ('WASTE', 'WASTE'), ('ADJUSTMENT', 'ADJUSTMENT'), ('RETURN', 'RETURN'), ('TRANSFER', 'TRANSFER'), ('COUNT', 'COUNT')], max_length=16)),
                ('quantity_delta', models.DecimalField(decimal_places=3, help_text='Signed: negative consumes stock.', max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=3, max_digits=14)),
                ('ref_type', models.CharField(blank=True, max_length=40)),
                ('ref_id', models.UUIDField(blank=True, null=True)),
                ('device_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'stock_movements',
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='KG, G, L, ML, PCS', max_length=16)),
                ('name_ar', models.CharField(max_length=50)),
                ('decimal_places', models.PositiveSmallIntegerField(default=3)),
            ],
            options={
                'db_table': 'units',
            },
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('factor', models.DecimalField(decimal_places=6, max_digits=16)),
            ],
            options={
                'db_table': 'unit_conversions',
            },
        ),
        migrations.CreateModel(
            name='CountLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_quantity', models.DecimalField(decimal_places=3, help_text='Snapshot when the line was added.', max_digits=14)),
                ('counted_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stock_count_lines',
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='level', serialize=False, to='inventory.inventoryitem')),
                ('quantity_on_hand', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('quantity_reserved', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Committed to open, unpaid orders — so low-stock alerts reflect reality.', max_digits=14)),
                ('weighted_avg_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('last_movement_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_levels',
            },
        ),
    ]
