# Generated by Django 5.2.17 on 2026-08-08 09:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyDaily',
            fields=[
                ('business_date', models.DateField(db_index=True)),
                ('boundary', models.TimeField(help_text='The finance.business_day_start this row was computed under (A5).')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hour', models.PositiveSmallIntegerField()),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('net_sales', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.branch')),
            ],
            options={
                'db_table': 'rollup_hourly_daily',
                'ordering': ['business_date', 'hour'],
                'constraints': [models.UniqueConstraint(fields=('branch', 'business_date', 'hour'), name='uniq_hourly_daily')],
            },
        ),
        migrations.CreateModel(
            name='ProductDaily',
            fields=[
                ('business_date', models.DateField(db_index=True)),
                ('boundary', models.TimeField(help_text='The finance.business_day_start this row was computed under (A5).')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_snapshot', models.CharField(help_text="As sold. A later rename must not rewrite what last month's report says.", max_length=250)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('void_count', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.branch')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.category')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.productvariant')),
            ],
            options={
                'db_table': 'rollup_product_daily',
                'ordering': ['-business_date', '-revenue'],
                'indexes': [models.Index(fields=['branch', 'business_date'], name='idx_product_daily_day')],
                'constraints': [models.UniqueConstraint(fields=('branch', 'business_date', 'variant'), name='uniq_product_daily')],
            },
        ),
        migrations.CreateModel(
            name='SalesDaily',
            fields=[
                ('business_date', models.DateField(db_index=True)),
                ('boundary', models.TimeField(help_text='The finance.business_day_start this row was computed under (A5).')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gross_sales', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('discounts', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('service', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('net_sales', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('refunds', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cash_sales', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('non_cash_sales', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cogs', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Recipe cost of what was sold.', max_digits=14)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('void_count', models.PositiveIntegerField(default=0)),
                ('item_count', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('average_ticket', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.branch')),
            ],
            options={
                'db_table': 'rollup_sales_daily',
                'ordering': ['-business_date'],
                'constraints': [models.UniqueConstraint(fields=('branch', 'business_date'), name='uniq_sales_daily')],
            },
        ),
    ]
