# Generated by Django 5.2.17 on 2026-08-11 21:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_date', models.DateField()),
                ('checked_in_at', models.DateTimeField()),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('TERMINAL', 'TERMINAL'), ('MANAGER', 'MANAGER'), ('AMENDED', 'AMENDED')], max_length=10)),
                ('amended_in_at', models.DateTimeField(blank=True, null=True)),
                ('amended_out_at', models.DateTimeField(blank=True, null=True)),
                ('amendment_reason', models.CharField(blank=True, max_length=200)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('amended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_amendments', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_attendance',
                'ordering': ['-business_date', '-checked_in_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('CHECK_IN', 'CHECK_IN'), ('CHECK_OUT', 'CHECK_OUT'), ('AMENDED', 'AMENDED')], max_length=10)),
                ('at', models.DateTimeField()),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hr.attendance')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_attendance_events',
                'ordering': ['at'],
            },
        ),
        migrations.CreateModel(
            name='WorkPattern',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('name_ar', models.CharField(max_length=100)),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField()),
                ('grace_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_work_patterns',
                'ordering': ['starts_at', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='hr.workpattern')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_work_shifts',
                'ordering': ['-business_date', 'user__full_name_ar'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance', to='hr.workshift'),
        ),
        migrations.AddConstraint(
            model_name='workpattern',
            constraint=models.UniqueConstraint(fields=('branch', 'name_ar'), name='uniq_hr_pattern_name_per_branch'),
        ),
        migrations.AddIndex(
            model_name='workshift',
            index=models.Index(fields=['branch', 'business_date'], name='idx_hr_shift_branch_date'),
        ),
        migrations.AddConstraint(
            model_name='workshift',
            constraint=models.UniqueConstraint(fields=('user', 'business_date'), name='uniq_hr_shift_per_person_per_day'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['branch', 'business_date'], name='idx_hr_att_branch_date'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['user', '-business_date'], name='idx_hr_att_user_date'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('user', 'business_date'), name='uniq_hr_attendance_per_person_per_day'),
        ),
    ]
