# Generated by Django 5.2.17 on 2026-08-07 08:43

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('key_prefix', models.CharField(help_text='QSR-7X29, for display.', max_length=16)),
                ('key_last4', models.CharField(max_length=8)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('license_type', models.CharField(choices=[('TRIAL', 'TRIAL'), ('MONTHLY', 'MONTHLY'), ('YEARLY', 'YEARLY'), ('LIFETIME', 'LIFETIME')], default='YEARLY', max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACTIVE', 'ACTIVE'), ('SUSPENDED', 'SUSPENDED'), ('EXPIRED', 'EXPIRED'), ('REVOKED', 'REVOKED')], default='PENDING', max_length=16)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Null = lifetime.', null=True)),
                ('max_devices', models.PositiveIntegerField(default=3)),
                ('activation_count', models.PositiveIntegerField(default=0)),
                ('last_activation_at', models.DateTimeField(blank=True, null=True)),
                ('token_seq', models.PositiveBigIntegerField(default=0, help_text='Monotonic counter stamped into offline tokens; drives the client ratchet.')),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Bound at first activation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'licenses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=100)),
                ('secret_hash', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('POS', 'POS'), ('KDS', 'KDS'), ('BOTH', 'BOTH')], default='POS', max_length=8)),
                ('platform', models.CharField(blank=True, max_length=64)),
                ('app_version', models.CharField(blank=True, max_length=32)),
                ('fingerprint', models.CharField(blank=True, help_text='Advisory telemetry only. Never authorizes.', max_length=128)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('SUSPENDED', 'SUSPENDED'), ('REVOKED', 'REVOKED')], default='ACTIVE', max_length=16)),
                ('first_activated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fingerprint_changed_count', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='licensing.license')),
            ],
            options={
                'db_table': 'devices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LicenseEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('CREATED', 'CREATED'), ('ACTIVATED', 'ACTIVATED'), ('ACTIVATION_FAILED', 'ACTIVATION_FAILED'), ('SUSPENDED', 'SUSPENDED'), ('RESUMED', 'RESUMED'), ('RENEWED', 'RENEWED'), ('REVOKED', 'REVOKED'), ('SEATS_CHANGED', 'SEATS_CHANGED'), ('KEY_REGENERATED', 'KEY_REGENERATED'), ('DEVICE_REVOKED', 'DEVICE_REVOKED'), ('DEVICE_RESET', 'DEVICE_RESET'), ('HEARTBEAT_DENIED', 'HEARTBEAT_DENIED')], max_length=32)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='licensing.device')),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='licensing.license')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'license_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceBlock',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('range_start', models.PositiveBigIntegerField()),
                ('range_end', models.PositiveBigIntegerField()),
                ('next_unused', models.PositiveBigIntegerField()),
                ('allocated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exhausted_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_blocks', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_blocks', to='licensing.device')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoice_blocks',
                'ordering': ['range_start'],
                'indexes': [models.Index(fields=['device', 'exhausted_at'], name='idx_block_device_open')],
                'constraints': [models.UniqueConstraint(fields=('branch', 'range_start'), name='uniq_block_start_per_branch'), models.CheckConstraint(condition=models.Q(('range_end__gte', models.F('range_start'))), name='block_range_is_ordered')],
            },
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['organization', 'status'], name='idx_license_org_status'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['branch', 'status'], name='idx_device_branch_status'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('license', 'device_name'), name='uniq_device_name_per_license'),
        ),
        migrations.AddIndex(
            model_name='licenseevent',
            index=models.Index(fields=['license', '-created_at'], name='idx_licevent_lic_time'),
        ),
    ]
