# Generated by Django 5.2.17 on 2026-08-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseevent',
            name='event',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('ACTIVATED', 'ACTIVATED'), ('ACTIVATION_FAILED', 'ACTIVATION_FAILED'), ('SUSPENDED', 'SUSPENDED'), ('RESUMED', 'RESUMED'), ('RENEWED', 'RENEWED'), ('REVOKED', 'REVOKED'), ('SEATS_CHANGED', 'SEATS_CHANGED'), ('KEY_REGENERATED', 'KEY_REGENERATED'), ('DEVICE_REVOKED', 'DEVICE_REVOKED'), ('DEVICE_RESET', 'DEVICE_RESET'), ('DEVICE_UNLOCKED', 'DEVICE_UNLOCKED'), ('HEARTBEAT_DENIED', 'HEARTBEAT_DENIED')], max_length=32),
        ),
    ]
