# Generated by Django 5.2.17 on 2026-08-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0002_alter_licenseevent_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='key_plaintext',
            field=models.CharField(blank=True, default='', help_text='Demo mode only. Empty on any real installation.', max_length=32),
        ),
    ]
