# Generated by Django 5.2.17 on 2026-08-16 19:37

"""
Customer identity stops being required on a licence.

This is a single-café product: the organisation IS the customer, and these two
columns were a second copy of its identity — free to drift from the first, and
read by nothing once activation stopped asking for an email. Kept rather than
dropped, because a column that once held real addresses is not worth deleting
to save two rows of schema.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0003_license_key_plaintext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='customer_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='license',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
