# Generated by Django 5.2.17 on 2026-08-09 09:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh', models.CharField(max_length=200)),
                ('auth', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('failures', models.PositiveSmallIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'push_subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'branch'], name='idx_push_user_branch')],
            },
        ),
        migrations.CreateModel(
            name='SentAlert',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('CASH_VARIANCE', 'CASH_VARIANCE'), ('KITCHEN_LATE', 'KITCHEN_LATE'), ('KIDS_OVERDUE', 'KIDS_OVERDUE'), ('TERMINAL_OFFLINE', 'TERMINAL_OFFLINE'), ('BACKUP_FAILED', 'BACKUP_FAILED'), ('SYNC_CONFLICT', 'SYNC_CONFLICT')], max_length=24)),
                ('dedupe_key', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('url', models.CharField(blank=True, max_length=200)),
                ('delivered', models.PositiveSmallIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_alerts', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sent_alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['branch', '-created_at'], name='idx_alert_branch_time')],
                'constraints': [models.UniqueConstraint(fields=('branch', 'kind', 'dedupe_key'), name='uniq_alert_per_subject')],
            },
        ),
    ]
