# Generated by Django 5.2.17 on 2026-08-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentalert',
            name='kind',
            field=models.CharField(choices=[('CASH_VARIANCE', 'CASH_VARIANCE'), ('KITCHEN_LATE', 'KITCHEN_LATE'), ('KIDS_OVERDUE', 'KIDS_OVERDUE'), ('TERMINAL_OFFLINE', 'TERMINAL_OFFLINE'), ('BACKUP_FAILED', 'BACKUP_FAILED'), ('SYNC_CONFLICT', 'SYNC_CONFLICT'), ('LOW_STOCK', 'LOW_STOCK')], max_length=24),
        ),
    ]
