# Generated by Django 5.2.17 on 2026-08-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='synced_permissions',
            field=models.JSONField(blank=True, default=list, help_text="The shipped spec as of the last sync. Lets ensure_system_roles tell 'a new code was added to the product' apart from 'an admin removed this on purpose' — without it, every deploy silently restores permissions an operator deliberately took away."),
        ),
    ]
