# Generated by Django 5.2.17 on 2026-08-07 17:32

import apps.core.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_initial'),
        ('orders', '0003_alter_orderevent_event_type'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=32)),
                ('national_id', models.CharField(blank=True, max_length=32)),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kids_guardians',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('age_months_snapshot', models.PositiveSmallIntegerField(default=0)),
                ('medical_notes', models.TextField(blank=True, help_text='Allergies, conditions staff must know about.')),
                ('consent_recorded', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='kids.guardian')),
            ],
            options={
                'db_table': 'kids_children',
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='PlayArea',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('name_ar', models.CharField(default='صالة الأطفال', max_length=100)),
                ('max_capacity', models.PositiveSmallIntegerField(default=25)),
                ('min_age_months', models.PositiveSmallIntegerField(default=12)),
                ('max_age_months', models.PositiveSmallIntegerField(default=144)),
                ('requires_socks', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('billing_variant', models.ForeignKey(blank=True, help_text='The service product a session is billed as. Overrides `kids.billing_product`. The price comes from the tariff, never from the variant — this only gives the sale a place in the catalog.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.productvariant')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('socks_variant', models.ForeignKey(blank=True, help_text='Added to the order at check-in when socks are required.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.productvariant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kids_areas',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='PlaySession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('order_line_id', models.UUIDField(blank=True, help_text='The order line this session became.', null=True)),
                ('device_id', models.UUIDField(blank=True, null=True)),
                ('tag_number', models.CharField(help_text='The wristband. What staff shout.', max_length=16)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('OVERDUE', 'OVERDUE'), ('CHECKED_OUT', 'CHECKED_OUT'), ('CANCELLED', 'CANCELLED')], default='ACTIVE', max_length=16)),
                ('checked_in_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expected_end_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('tariff_name_snapshot', models.CharField(blank=True, max_length=100)),
                ('tariff_snapshot', models.JSONField(blank=True, default=dict)),
                ('rounding_snapshot', models.CharField(blank=True, max_length=16)),
                ('grace_minutes_snapshot', models.PositiveSmallIntegerField(default=0)),
                ('billable_minutes', models.PositiveIntegerField(default=0)),
                ('computed_charge', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('override_charge', models.DecimalField(blank=True, decimal_places=2, help_text='Sits BESIDE the computed figure, never replaces it.', max_digits=12, null=True)),
                ('override_reason', models.CharField(blank=True, max_length=200)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='kids.playarea')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.branch')),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='kids.child')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='kids.guardian')),
                ('order', models.ForeignKey(blank=True, help_text='Null until the session is billed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='play_sessions', to='orders.order')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('override_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('release_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('released_to_guardian', models.ForeignKey(blank=True, help_text="Who ACTUALLY collected the child, which may legitimately differ from who registered them. Storing it makes the handover an auditable fact rather than someone's memory.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='kids.guardian')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kids_sessions',
                'ordering': ['-checked_in_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayIncident',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_type', models.CharField(choices=[('INJURY', 'INJURY'), ('DISPUTE', 'DISPUTE'), ('LOST_ITEM', 'LOST_ITEM'), ('CAPACITY', 'CAPACITY'), ('OTHER', 'OTHER')], default='OTHER', max_length=16)),
                ('description', models.TextField()),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='kids.playarea')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='kids.playsession')),
            ],
            options={
                'db_table': 'kids_incidents',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayTariff',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('name_ar', models.CharField(max_length=100)),
                ('mode', models.CharField(choices=[('TIMED', 'TIMED'), ('PACKAGE', 'PACKAGE'), ('OPEN_DAY', 'OPEN_DAY')], default='TIMED', max_length=16)),
                ('entry_fee', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('included_minutes', models.PositiveSmallIntegerField(default=0, help_text='TIMED: what the entry fee covers.')),
                ('package_minutes', models.PositiveSmallIntegerField(default=0, help_text='PACKAGE: the fixed duration the flat fee buys.')),
                ('block_minutes', models.PositiveSmallIntegerField(default=0)),
                ('block_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('grace_minutes', models.PositiveSmallIntegerField(blank=True, help_text="Null = use the branch's kids.grace_minutes.", null=True)),
                ('daily_cap', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='0 = uncapped.', max_digits=12)),
                ('applies_days', models.JSONField(blank=True, default=list, help_text='Monday=0. Empty = every day.')),
                ('applies_from', models.TimeField(blank=True, null=True)),
                ('applies_to', models.TimeField(blank=True, null=True)),
                ('priority', models.SmallIntegerField(default=0, help_text='Highest matching priority wins at check-in.')),
                ('is_default', models.BooleanField(default=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='kids.playarea')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kids_tariffs',
                'ordering': ['-priority', 'name_ar'],
            },
        ),
        migrations.AddField(
            model_name='playsession',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='kids.playtariff'),
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['branch', 'phone'], name='idx_guardian_phone'),
        ),
        migrations.AddIndex(
            model_name='playsession',
            index=models.Index(fields=['branch', 'status'], name='idx_session_branch_status'),
        ),
        migrations.AddIndex(
            model_name='playsession',
            index=models.Index(fields=['branch', '-checked_in_at'], name='idx_session_branch_time'),
        ),
        migrations.AddConstraint(
            model_name='playsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['ACTIVE', 'OVERDUE'])), fields=('area', 'tag_number'), name='uniq_open_tag_per_area'),
        ),
    ]
