# Generated by Django 5.2.17 on 2026-08-08 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=200, unique=True)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, help_text='Of the file as written. What a restore checks before trusting it.', max_length=64)),
                ('encrypted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('RUNNING', 'RUNNING'), ('COMPLETE', 'COMPLETE'), ('FAILED', 'FAILED')], default='RUNNING', max_length=12)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('triggered_by', models.ForeignKey(blank=True, help_text='Null for the scheduled nightly run.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ops_backups',
                'ordering': ['-started_at'],
            },
        ),
    ]
