# Generated by Django 5.2.17 on 2026-08-07 16:58

import apps.core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
        ('orders', '0002_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='printer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='station',
            name='auto_accept',
            field=models.BooleanField(default=False, help_text='Skip the ACCEPTED step for stations that never triage, e.g. a bar.'),
        ),
        migrations.CreateModel(
            name='KitchenTicket',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.PositiveIntegerField(help_text='Per branch per day — what staff shout.')),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('ACCEPTED', 'ACCEPTED'), ('PREPARING', 'PREPARING'), ('READY', 'READY'), ('SERVED', 'SERVED'), ('CANCELLED', 'CANCELLED')], default='NEW', max_length=16)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('prep_seconds', models.PositiveIntegerField(blank=True, help_text='Fired to ready. The raw material for the delay report.', null=True)),
                ('printed', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kitchen_tickets', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_tickets', to='orders.order')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='kitchen.station')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kitchen_tickets',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_snapshot', models.CharField(max_length=250)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('modifiers_snapshot', models.JSONField(blank=True, default=list)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('ready_at', models.DateTimeField(blank=True, help_text='Per-item readiness, for stations that plate in stages.', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_lines', to='orders.orderitem')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='kitchen.kitchenticket')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kitchen_ticket_lines',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='kitchenticket',
            index=models.Index(fields=['branch', 'status'], name='idx_ticket_branch_status'),
        ),
        migrations.AddIndex(
            model_name='kitchenticket',
            index=models.Index(fields=['station', 'status'], name='idx_ticket_station_status'),
        ),
        migrations.AddIndex(
            model_name='kitchenticket',
            index=models.Index(fields=['order'], name='idx_ticket_order'),
        ),
    ]
