# Generated by Django 5.2.17 on 2026-08-07 22:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licensing', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('op_uuid', models.UUIDField(db_index=True, unique=True)),
                ('batch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('entity_type', models.CharField(max_length=48)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPLIED', 'APPLIED'), ('CONFLICT', 'CONFLICT'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=12)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=48)),
                ('error_message', models.TextField(blank=True)),
                ('client_seq', models.BigIntegerField(blank=True, help_text="The device's outbox ordering. Preserves causality.", null=True)),
                ('aggregate_seq', models.IntegerField(blank=True, help_text="The device's per-aggregate sequence, e.g. this order's 4th event from this terminal. What SEQUENCE_GAP detection compares against — the server assigns its own order sequence, so the client's number is only useful for spotting a hole in the device's own stream.", null=True)),
                ('client_time', models.DateTimeField(blank=True, help_text="The device's clock — may be skewed.", null=True)),
                ('clock_skew_seconds', models.IntegerField(default=0, help_text='client_time − server time at receipt. Recorded, never used for anything.')),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_operations', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='licensing.device')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_operations',
                'ordering': ['received_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncConflict',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=48)),
                ('message_ar', models.CharField(max_length=250)),
                ('server_state', models.JSONField(blank=True, default=dict, help_text='What the server believed, so the human can compare.')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, max_length=32)),
                ('resolution_note', models.CharField(blank=True, max_length=250)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_conflicts', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='sync.syncoperation')),
            ],
            options={
                'db_table': 'sync_conflicts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('seq', models.BigAutoField(primary_key=True, serialize=False)),
                ('stream', models.CharField(choices=[('config', 'config'), ('catalog', 'catalog'), ('floor', 'floor'), ('staff', 'staff'), ('orders', 'orders'), ('kids', 'kids')], max_length=16)),
                ('entity_type', models.CharField(max_length=48)),
                ('entity_id', models.UUIDField()),
                ('operation', models.CharField(choices=[('UPSERT', 'UPSERT'), ('DELETE', 'DELETE')], max_length=8)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('txid', models.BigIntegerField(db_index=True, help_text="The Postgres transaction that wrote this row (pg_current_xact_id). A pull never serves rows from a transaction that might still be in flight, which is what stops a concurrent writer's row from landing behind a cursor that has already moved past it.")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='organizations.branch')),
            ],
            options={
                'db_table': 'sync_change_log',
                'ordering': ['seq'],
                'indexes': [models.Index(fields=['branch', 'stream', 'seq'], name='idx_change_branch_stream')],
            },
        ),
        migrations.CreateModel(
            name='DeviceCursor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stream', models.CharField(choices=[('config', 'config'), ('catalog', 'catalog'), ('floor', 'floor'), ('staff', 'staff'), ('orders', 'orders'), ('kids', 'kids')], max_length=16)),
                ('cursor', models.BigIntegerField(default=0)),
                ('last_pulled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursors', to='licensing.device')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_device_cursors',
                'constraints': [models.UniqueConstraint(fields=('device', 'stream'), name='uniq_cursor_per_stream')],
            },
        ),
        migrations.AddIndex(
            model_name='syncoperation',
            index=models.Index(fields=['branch', 'status'], name='idx_op_branch_status'),
        ),
        migrations.AddIndex(
            model_name='syncoperation',
            index=models.Index(fields=['device', '-received_at'], name='idx_op_device_time'),
        ),
        migrations.AddIndex(
            model_name='syncconflict',
            index=models.Index(fields=['branch', 'resolved_at'], name='idx_conflict_branch_open'),
        ),
    ]
