# Generated by Django 5.2.17 on 2026-08-07 16:05

import apps.core.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('event_type', models.CharField(choices=[('ORDER_OPENED', 'ORDER_OPENED'), ('ITEM_ADDED', 'ITEM_ADDED'), ('ITEM_QUANTITY_CHANGED', 'ITEM_QUANTITY_CHANGED'), ('ITEM_VOIDED', 'ITEM_VOIDED'), ('ITEM_NOTE_SET', 'ITEM_NOTE_SET'), ('DISCOUNT_APPLIED', 'DISCOUNT_APPLIED'), ('ORDER_FIRED', 'ORDER_FIRED'), ('TABLE_ASSIGNED', 'TABLE_ASSIGNED'), ('CUSTOMER_ASSIGNED', 'CUSTOMER_ASSIGNED'), ('PAYMENT_TAKEN', 'PAYMENT_TAKEN'), ('ORDER_CLOSED', 'ORDER_CLOSED'), ('ORDER_VOIDED', 'ORDER_VOIDED')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('device_id', models.UUIDField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(help_text='Client clock — may be skewed.')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='Server clock — authoritative.')),
            ],
            options={
                'db_table': 'order_events',
                'ordering': ['order', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_id', models.UUIDField(help_text='Client-minted; the id events refer to.')),
                ('name_snapshot', models.CharField(max_length=250)),
                ('unit_price_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('tax_exempt_snapshot', models.BooleanField(default=False)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('line_gross', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('line_discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('VOIDED', 'VOIDED')], default='ACTIVE', max_length=8)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('fired_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'order_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemModifier',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_snapshot', models.CharField(max_length=150)),
                ('price_delta_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
            ],
            options={
                'db_table': 'order_item_modifiers',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.UUIDField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=32)),
                ('local_number', models.CharField(help_text='MB-01-0042 — readable, unique per device.', max_length=32)),
                ('order_type', models.CharField(choices=[('DINE_IN', 'DINE_IN'), ('TAKE_AWAY', 'TAKE_AWAY'), ('DELIVERY', 'DELIVERY')], default='DINE_IN', max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('OPEN', 'OPEN'), ('IN_KITCHEN', 'IN_KITCHEN'), ('READY', 'READY'), ('SERVED', 'SERVED'), ('PAID', 'PAID'), ('CANCELLED', 'CANCELLED'), ('REFUNDED', 'REFUNDED')], default='DRAFT', max_length=16)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('service_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('vat_inclusive', models.BooleanField(default=False)),
                ('rounding_step', models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=6)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('discount_reason', models.CharField(blank=True, max_length=200)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('service_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('rounding_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('paid_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('opened_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=200)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-opened_at'],
            },
        ),
    ]
