# Generated by Django 5.2.17 on 2026-08-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevent',
            name='event_type',
            field=models.CharField(choices=[('ORDER_OPENED', 'ORDER_OPENED'), ('ITEM_ADDED', 'ITEM_ADDED'), ('ITEM_QUANTITY_CHANGED', 'ITEM_QUANTITY_CHANGED'), ('ITEM_VOIDED', 'ITEM_VOIDED'), ('ITEM_NOTE_SET', 'ITEM_NOTE_SET'), ('DISCOUNT_APPLIED', 'DISCOUNT_APPLIED'), ('ORDER_FIRED', 'ORDER_FIRED'), ('PLAY_SESSION_CHARGED', 'PLAY_SESSION_CHARGED'), ('TABLE_ASSIGNED', 'TABLE_ASSIGNED'), ('CUSTOMER_ASSIGNED', 'CUSTOMER_ASSIGNED'), ('PAYMENT_TAKEN', 'PAYMENT_TAKEN'), ('ORDER_CLOSED', 'ORDER_CLOSED'), ('ORDER_VOIDED', 'ORDER_VOIDED')], max_length=32),
        ),
    ]
