# Generated by Django 5.2.17 on 2026-08-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_override_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='event_type',
            field=models.CharField(choices=[('ORDER_OPENED', 'ORDER_OPENED'), ('ITEM_ADDED', 'ITEM_ADDED'), ('ITEM_QUANTITY_CHANGED', 'ITEM_QUANTITY_CHANGED'), ('ITEM_VOIDED', 'ITEM_VOIDED'), ('ITEM_NOTE_SET', 'ITEM_NOTE_SET'), ('ITEM_PRICE_OVERRIDDEN', 'ITEM_PRICE_OVERRIDDEN'), ('DISCOUNT_APPLIED', 'DISCOUNT_APPLIED'), ('ORDER_FIRED', 'ORDER_FIRED'), ('PLAY_SESSION_CHARGED', 'PLAY_SESSION_CHARGED'), ('TABLE_ASSIGNED', 'TABLE_ASSIGNED'), ('CUSTOMER_ASSIGNED', 'CUSTOMER_ASSIGNED'), ('PAYMENT_TAKEN', 'PAYMENT_TAKEN'), ('ORDER_CLOSED', 'ORDER_CLOSED'), ('ORDER_VOIDED', 'ORDER_VOIDED')], max_length=32),
        ),
    ]
