# Generated by Django 5.2.17 on 2026-08-16 20:01

"""
A fourth channel: EXTERNAL — an order that arrived from outside the cafe.

Distinct from DELIVERY, which is the cafe's own driver taking out a bill
somebody rang for. An app takes a commission and sets its own menu price, so
the same latte is a different number and a different margin on each; reported
as one line, both are wrong.

Choices only — no data moves. Every existing order keeps the channel it was
sold on, which is the point: a receipt is a record of what happened.
"""


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_price_override_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('DINE_IN', 'DINE_IN'), ('TAKE_AWAY', 'TAKE_AWAY'), ('DELIVERY', 'DELIVERY'), ('EXTERNAL', 'EXTERNAL')], default='DINE_IN', max_length=16),
        ),
    ]
