# Generated by Django 5.2.17 on 2026-08-08 11:35

import apps.audit.actions
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=48)),
                ('domain', models.CharField(db_index=True, max_length=24)),
                ('severity', models.CharField(choices=[('INFO', 'INFO'), ('NOTICE', 'NOTICE'), ('WARNING', 'WARNING')], default=apps.audit.actions.Severity['INFO'], max_length=8)),
                ('actor_name', models.CharField(blank=True, help_text='Snapshotted — a deleted user must still be nameable.', max_length=150)),
                ('approved_by_name', models.CharField(blank=True, max_length=150)),
                ('device_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('object_type', models.CharField(blank=True, max_length=48)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('object_label', models.CharField(blank=True, help_text="Human-readable, snapshotted: 'MB-01-0042'.", max_length=250)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Only the fields that moved: {field: [old, new]}.')),
                ('detail', models.JSONField(blank=True, default=dict, help_text='Context that is not a field change — a reason, an amount.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=250)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='organizations.organization')),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['organization', '-occurred_at'], name='idx_audit_org_time'), models.Index(fields=['branch', 'action'], name='idx_audit_branch_action'), models.Index(fields=['actor', '-occurred_at'], name='idx_audit_actor_time'), models.Index(fields=['object_type', 'object_id'], name='idx_audit_object')],
            },
        ),
    ]
