# Generated by Django 5.2.17 on 2026-08-08 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Null for events that belong to no tenant — a failed login against an address that does not exist. Dropping those would blind exactly the credential-stuffing case the record exists for, so they are kept and are visible only to a superuser.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='organizations.organization'),
        ),
    ]
