/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json
         */
        get: operations["schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolved settings for a scope
         * @description Resolved values for a scope, each tagged with where it came from.
         */
        get: operations["settings_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Write setting overrides
         * @description Resolved values for a scope, each tagged with where it came from.
         */
        patch: operations["settings_partial_update"];
        trace?: never;
    };
    "/api/v1/settings/{key}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Reset a setting to its inherited or default value */
        delete: operations["settings_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/history/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who changed what, and when */
        get: operations["settings_history_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Settings registry schema
         * @description The registry, as data.
         *
         *     The Web Admin renders its entire settings UI from this — grouped, typed,
         *     validated, with Arabic labels and help. A new setting appears in the UI
         *     with no frontend change.
         */
        get: operations["settings_schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Reports API liveness and database reachability.
         */
        get: operations["system_health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/info/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server and client version information
         * @description Version negotiation for Desktop clients (§61).
         *
         *     A client below `min_supported_client_version` is refused everything except
         *     the heartbeat — one that predates a breaking sync change must not be allowed
         *     to corrupt data by guessing at the new contract.
         */
        get: operations["system_info_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            status: components["schemas"]["StatusEnum"];
            version: string;
            checks: components["schemas"]["HealthChecks"];
        };
        HealthChecks: {
            database: boolean;
        };
        /**
         * @description * `ORGANIZATION` - ORGANIZATION
         *     * `BRANCH` - BRANCH
         *     * `DEVICE` - DEVICE
         *     * `ROLE` - ROLE
         *     * `DEFAULT` - DEFAULT
         * @enum {string}
         */
        OriginEnum: "ORGANIZATION" | "BRANCH" | "DEVICE" | "ROLE" | "DEFAULT";
        PatchedSettingWriteRequestRequest: {
            scope?: components["schemas"]["ScopeEnum"];
            /** Format: uuid */
            scope_id?: string;
            /** @description Setting key → new value. Each is validated independently. */
            values?: {
                [key: string]: unknown;
            };
        };
        ResolvedSetting: {
            value: unknown;
            origin: components["schemas"]["OriginEnum"];
            is_default: boolean;
        };
        /**
         * @description * `ORGANIZATION` - ORGANIZATION
         *     * `BRANCH` - BRANCH
         *     * `DEVICE` - DEVICE
         *     * `ROLE` - ROLE
         * @enum {string}
         */
        ScopeEnum: "ORGANIZATION" | "BRANCH" | "DEVICE" | "ROLE";
        SettingDefinition: {
            key: string;
            type: string;
            scope: string;
            default: unknown;
            label_ar: string;
            label_en: string;
            help_ar: string;
            choices: string[];
            permission: string;
            /** @description Financial, security or licensing — the UI confirms before saving. */
            high_impact: boolean;
            /** @description Applies only to orders opened after the change. */
            affects_open_orders: boolean;
            pushes_to_desktop: boolean;
        };
        SettingHistoryEntry: {
            key: string;
            scope_type: string;
            /** Format: uuid */
            scope_id: string;
            old_value: unknown;
            new_value: unknown;
            changed_by: string | null;
            ip_address: string | null;
            /** Format: date-time */
            created_at: string;
        };
        SettingHistoryResponse: {
            history: components["schemas"]["SettingHistoryEntry"][];
        };
        SettingListResponse: {
            settings: {
                [key: string]: components["schemas"]["ResolvedSetting"];
            };
        };
        SettingSchemaResponse: {
            groups: {
                [key: string]: components["schemas"]["SettingDefinition"][];
            };
            count: number;
        };
        SettingWriteResponse: {
            applied: {
                [key: string]: unknown;
            };
            /** @description Keys that failed validation. A 207 means the write was partial. */
            errors: {
                [key: string]: string[];
            };
        };
        /**
         * @description * `healthy` - healthy
         *     * `degraded` - degraded
         * @enum {string}
         */
        StatusEnum: "healthy" | "degraded";
        SystemInfo: {
            server_version: string;
            /** @description Clients below this are refused everything except the heartbeat. */
            min_supported_client_version: string;
            api_version: string;
        };
        ErrorEnvelope: {
            /** @enum {boolean} */
            success: false;
            /** @description Localized, safe to display. */
            message: string;
            /**
             * @description Stable machine-readable code. Never localized.
             * @example VALIDATION_ERROR
             */
            code: string;
            /** @description Per-field messages, for form binding. */
            errors?: {
                [key: string]: string[];
            };
            meta?: {
                /** @description Correlates this response with server logs. */
                request_id?: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    schema_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "ar" | "en";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        /** @enum {boolean} */
                        success: true;
                        data: {
                            [key: string]: unknown;
                        };
                        meta?: {
                            /** @description Correlates this response with server logs. */
                            request_id?: string;
                        };
                    };
                    "application/yaml": {
                        /** @enum {boolean} */
                        success: true;
                        data: {
                            [key: string]: unknown;
                        };
                        meta?: {
                            /** @description Correlates this response with server logs. */
                            request_id?: string;
                        };
                    };
                    "application/vnd.oai.openapi+json": {
                        /** @enum {boolean} */
                        success: true;
                        data: {
                            [key: string]: unknown;
                        };
                        meta?: {
                            /** @description Correlates this response with server logs. */
                            request_id?: string;
                        };
                    };
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: {
                            [key: string]: unknown;
                        };
                        meta?: {
                            /** @description Correlates this response with server logs. */
                            request_id?: string;
                        };
                    };
                };
            };
        };
    };
    settings_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["SettingListResponse"];
                        meta?: {
                            /** @description Correlates this response with server logs. */
                            request_id?: string;
                        };
                    };
                };
            };
        };
    };
    settings_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSettingWriteRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSettingWriteRequestRequest"];
                "multipart/form-data": components["schemas"]["PatchedSettingWriteRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["SettingWriteResponse"];
                        meta?: {
                            /** @description Correlates this response with server logs. */
                            request_id?: string;
                        };
                    };
                };
            };
            207: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["SettingWriteResponse"];
                        meta?: {
                            /** @description Correlates this response with server logs. */
                            request_id?: string;
                        };
                    };
                };
            };
        };
    };
    settings_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    settings_history_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["SettingHistoryResponse"];
                        meta?: {
                            /** @description Correlates this response with server logs. */
                            request_id?: string;
                        };
                    };
                };
            };
        };
    };
    settings_schema_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["SettingSchemaResponse"];
                        meta?: {
                            /** @description Correlates this response with server logs. */
                            request_id?: string;
                        };
                    };
                };
            };
        };
    };
    system_health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["Health"];
                        meta?: {
                            /** @description Correlates this response with server logs. */
                            request_id?: string;
                        };
                    };
                };
            };
            /** @description No response body */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    system_info_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["SystemInfo"];
                        meta?: {
                            /** @description Correlates this response with server logs. */
                            request_id?: string;
                        };
                    };
                };
            };
        };
    };
}
