# Generated by Django 5.2.17 on 2026-08-07 16:05

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSING', 'CLOSING'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=8)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('counted_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('variance_reason', models.CharField(blank=True, max_length=200)),
                ('opened_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('z_report', models.JSONField(blank=True, default=dict, help_text='Frozen at close.')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.branch')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shifts',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT'), ('EXPENSE', 'EXPENSE'), ('DROP', 'DROP')], max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Always positive; the type carries direction.', max_digits=12)),
                ('reason', models.CharField(max_length=200)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='shifts.shift')),
            ],
            options={
                'db_table': 'cash_movements',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['branch', 'status'], name='idx_shift_branch_status'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('device_id',), name='one_open_shift_per_device'),
        ),
    ]
