# Generated by Django 5.2.17 on 2026-08-09 12:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kitchen', '0002_station_printer_name_alter_station_auto_accept_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('name_ar', models.CharField(help_text='طابعة الكاشير / طابعة المطبخ', max_length=100)),
                ('code', models.CharField(help_text='RECEIPT1, KITCHEN_HOT', max_length=32)),
                ('kind', models.CharField(choices=[('RECEIPT', 'RECEIPT'), ('KITCHEN', 'KITCHEN'), ('REPORT', 'REPORT')], default='RECEIPT', max_length=8)),
                ('connection', models.CharField(choices=[('NETWORK', 'NETWORK'), ('USB', 'USB'), ('WINDOWS', 'WINDOWS')], default='NETWORK', max_length=8)),
                ('host', models.CharField(blank=True, max_length=100)),
                ('port', models.PositiveIntegerField(default=9100)),
                ('device_path', models.CharField(blank=True, max_length=200)),
                ('paper_width_mm', models.PositiveSmallIntegerField(default=80)),
                ('copies', models.PositiveSmallIntegerField(default=1)),
                ('cut_after', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Where a job of this kind goes when nothing else claims it.')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('stations', models.ManyToManyField(blank=True, related_name='printers', to='kitchen.station')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'printers',
                'ordering': ['kind', 'name_ar'],
                'constraints': [models.UniqueConstraint(fields=('branch', 'code'), name='uniq_printer_code_per_branch'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('branch', 'kind'), name='one_default_printer_per_kind'), models.CheckConstraint(condition=models.Q(('paper_width_mm__in', [58, 80])), name='printer_paper_is_a_real_roll')],
            },
        ),
    ]
