# Generated by Django 5.2.17 on 2026-08-07 15:43

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_ar', models.CharField(max_length=100)),
                ('min_select', models.PositiveSmallIntegerField(default=0)),
                ('max_select', models.PositiveSmallIntegerField(default=1)),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'modifier_groups',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('effective_from', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'price_history',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('sku', models.CharField(max_length=32)),
                ('barcode', models.CharField(blank=True, max_length=64)),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('description_ar', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('tax_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Null = use the branch VAT rate.', max_digits=5, null=True)),
                ('is_tax_exempt', models.BooleanField(default=False)),
                ('track_inventory', models.BooleanField(default=True, help_text='False for items with no recipe, e.g. a bought-in bottle.')),
                ('is_sellable', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['sort_order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='ProductModifierGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'product_modifier_groups',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('name_ar', models.CharField(blank=True, help_text='وسط / كبير. Blank if sole.', max_length=100)),
                ('sku', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Computed from the recipe. Never entered by hand.', max_digits=12)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'product_variants',
                'ordering': ['sort_order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, help_text='#RRGGBB for the POS grid.', max_length=9)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['sort_order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('name_ar', models.CharField(max_length=100)),
                ('price_delta', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('quantity_consumed', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'modifiers',
                'ordering': ['sort_order', 'name_ar'],
            },
        ),
    ]
