# Generated by Django 5.2.17 on 2026-08-07 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('kitchen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='station',
            field=models.ForeignKey(blank=True, help_text='Where this is prepared. Drives kitchen ticket routing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='kitchen.station'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productmodifiergroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.modifiergroup'),
        ),
        migrations.AddField(
            model_name='productmodifiergroup',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_groups', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='catalog.productvariant'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['branch', 'is_active'], name='idx_category_branch_active'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['branch', 'category', 'sort_order'], name='idx_product_grid'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['branch', 'barcode'], name='idx_product_barcode'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('branch', 'sku'), name='uniq_sku_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='productmodifiergroup',
            constraint=models.UniqueConstraint(fields=('product', 'group'), name='uniq_group_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'sku'), name='uniq_variant_sku_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('product',), name='one_default_variant_per_product'),
        ),
    ]
