# Generated by Django 5.2.17 on 2026-08-07 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenfamily',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Null for DEVICE sessions — a terminal is not a person.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_families', to=settings.AUTH_USER_MODEL),
        ),
    ]
