# Generated by Django 5.2.17 on 2026-08-06 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingChangeLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scope_type', models.CharField(max_length=20)),
                ('scope_id', models.UUIDField()),
                ('key', models.CharField(max_length=100)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'setting_change_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key', '-created_at'], name='idx_settinglog_key')],
            },
        ),
        migrations.CreateModel(
            name='SettingValue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scope_type', models.CharField(choices=[('ORGANIZATION', 'ORGANIZATION'), ('BRANCH', 'BRANCH'), ('DEVICE', 'DEVICE'), ('ROLE', 'ROLE')], max_length=20)),
                ('scope_id', models.UUIDField()),
                ('key', models.CharField(max_length=100)),
                ('value', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'setting_values',
                'indexes': [models.Index(fields=['scope_type', 'scope_id'], name='idx_setting_scope'), models.Index(fields=['key'], name='idx_setting_key')],
                'constraints': [models.UniqueConstraint(fields=('scope_type', 'scope_id', 'key'), name='uniq_setting_per_scope')],
            },
        ),
    ]
