#!/usr/bin/env python3
"""
Copy the shared logic modules from the backend into the Desktop client.

Some rules must produce identical answers on both sides — order totals to the
piaster, offline-token verification, licence-key normalization. Reimplementing
them in the client is how a server and a client start quietly disagreeing about
a number, so the client vendors the backend's modules verbatim.

    python scripts/vendor_shared.py           # copy
    python scripts/vendor_shared.py --check   # verify they are in sync (CI)

The `--check` mode is what makes this safe: an edit to the backend copy that is
not vendored fails the build, so the two can never drift silently.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BACKEND = ROOT / "backend" / "apps"
VENDORED = ROOT / "desktop" / "src" / "caesar_pos" / "vendored"

#: (source relative to backend/apps, why it must be shared)
MODULES = [
    ("core/money.py", "order totals must agree to the piaster"),
    ("core/play_pricing.py", "a play session checked out offline must price identically"),
    ("licensing/offline_token.py", "the client verifies licence tokens locally"),
    ("licensing/keys.py", "the client normalizes typed keys before sending them"),
]

HEADER = """# ─────────────────────────────────────────────────────────────────────────────
# VENDORED — DO NOT EDIT THIS FILE.
#
# Copied verbatim from backend/apps/{source}
# Reason: {reason}
#
# Edit the backend copy, then run:  python scripts/vendor_shared.py
# CI fails if the two ever differ.
# ─────────────────────────────────────────────────────────────────────────────
"""


def _digest(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()[:12]


def _rendered(source: str, reason: str) -> str:
    body = (BACKEND / source).read_text(encoding="utf-8")
    return HEADER.format(source=source, reason=reason) + "\n" + body


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify without writing")
    args = parser.parse_args()

    VENDORED.mkdir(parents=True, exist_ok=True)
    init = VENDORED / "__init__.py"
    if not args.check and not init.exists():
        init.write_text(
            '"""Modules copied verbatim from the backend. Do not edit by hand."""\n',
            encoding="utf-8",
        )

    stale: list[str] = []
    for source, reason in MODULES:
        target = VENDORED / Path(source).name
        expected = _rendered(source, reason)

        if args.check:
            actual = target.read_text(encoding="utf-8") if target.exists() else ""
            if actual != expected:
                stale.append(
                    f"  {source}\n"
                    f"      backend: {_digest(expected)}   vendored: {_digest(actual) if actual else 'MISSING'}"
                )
            continue

        target.write_text(expected, encoding="utf-8")
        print(f"vendored  {source}  ->  {target.relative_to(ROOT)}")

    if stale:
        print("Vendored copies are out of sync with the backend:\n" + "\n".join(stale))
        print("\nRun:  python scripts/vendor_shared.py")
        return 1

    if args.check:
        print(f"{len(MODULES)} vendored modules are in sync.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
