# Generated by Django 5.2.17 on 2026-08-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='provisional_serial',
            field=models.CharField(blank=True, help_text="What a terminal printed after exhausting its block offline, e.g. MB-01-P042. Recorded beside the permanent serial so the slip in a customer's hand can still be matched to this invoice (C9).", max_length=32),
        ),
    ]
