# Generated by Django 5.2.17 on 2026-08-17 10:40

"""
A payment method becomes properly soft-deletable.

It carried `is_active` without inheriting `SoftDeletableModel`, which read as
soft-deletable and was not: `perform_destroy` stamps `deactivated_at`, so every
`DELETE /payments/methods/{id}/` returned 500 from the day it was routed. Nothing
noticed because nothing called it — there was no screen for payment methods.

The field also puts a retired tender in the recycle bin. These rows are on
historical payments, so switching one off must be recoverable; before this,
retiring «فيزا» by accident meant editing the database to take cards again.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_invoice_provisional_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
