# Generated by Django 5.2.17 on 2026-08-08 19:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='rotation',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='shape',
            field=models.CharField(choices=[('ROUND', 'ROUND'), ('SQUARE', 'SQUARE'), ('RECT', 'RECT'), ('BOOTH', 'BOOTH'), ('BAR', 'BAR')], default='SQUARE', max_length=8),
        ),
        migrations.AddField(
            model_name='table',
            name='span_x',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='table',
            name='span_y',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.CheckConstraint(condition=models.Q(('rotation__lt', 360)), name='table_rotation_is_a_bearing'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.CheckConstraint(condition=models.Q(('seats__gte', 1), ('seats__lte', 24)), name='table_seats_are_plausible'),
        ),
    ]
